import img1 from '../assets/FoodDelivery/wandy 6.png';
import img2 from '../assets/FoodDelivery/veggie 5.png';

export const foodData = [
  {
    id: 1,
    name: 'Cheeseburger',
    category: "Wendy's Burger",
    price: 120,
    rating: 4.9,
    img: img1,
  },
  {
    id: 2,
    name: 'Hamburger',
    category: 'Veggie Burger',
    price: 150,
    rating: 4.8,
    img: img2,
  },
  {
    id: 3,
    name: 'Hamburger',
    category: 'Chicken Burger',
    price: 220,
    rating: 4.6,
    img: 'img3',
  },
  {
    id: 4,
    name: 'Hamburger',
    category: 'Fried Chicken Burger',
    price: 180,
    rating: 4.5,
    img: 'img4',
  },

  {
    id: 5,
    name: 'Cheese Burger',
    category: 'Sliders',
    price: 100,
    rating: 4.7,
    img: 'img5',
  },
  {
    id: 6,
    name: 'Classic Slider',
    category: 'Sliders',
    price: 130,
    rating: 4.4,
    img: 'img6',
  },
  {
    id: 7,
    name: 'Chicken Slider',
    category: 'Sliders',
    price: 160,
    rating: 4.8,
    img: 'img7',
  },
  {
    id: 8,
    name: 'BBQ Slider',
    category: 'Sliders',
    price: 170,
    rating: 4.6,
    img: 'img8',
  },
  {
    id: 9,
    name: 'Spicy Slider',
    category: 'Sliders',
    price: 150,
    rating: 4.5,
    img: 'img9',
  },
  {
    id: 10,
    name: 'Paneer Slider',
    category: 'Sliders',
    price: 140,
    rating: 4.3,
    img: 'img10',
  },

  {
    id: 11,
    name: 'Burger Combo',
    category: 'Combos',
    price: 250,
    rating: 4.5,
    img: 'img11',
  },
  {
    id: 12,
    name: 'Chicken Combo',
    category: 'Combos',
    price: 320,
    rating: 4.8,
    img: 'img12',
  },
  {
    id: 13,
    name: 'Family Combo',
    category: 'Combos',
    price: 550,
    rating: 4.9,
    img: 'img13',
  },
  {
    id: 14,
    name: 'Cheese Combo',
    category: 'Combos',
    price: 280,
    rating: 4.4,
    img: 'img14',
  },
  {
    id: 15,
    name: 'Mega Combo',
    category: 'Combos',
    price: 450,
    rating: 4.7,
    img: 'img15',
  },
  {
    id: 16,
    name: 'Party Combo',
    category: 'Combos',
    price: 650,
    rating: 4.9,
    img: 'img16',
  },
  {
    id: 17,
    name: 'Friends Combo',
    category: 'Combos',
    price: 500,
    rating: 4.6,
    img: 'img17',
  },
  {
    id: 18,
    name: 'Lunch Combo',
    category: 'Combos',
    price: 300,
    rating: 4.3,
    img: 'img18',
  },
  {
    id: 19,
    name: 'Snack Combo',
    category: 'Combos',
    price: 220,
    rating: 4.2,
    img: 'img19',
  },
  {
    id: 20,
    name: 'Premium Combo',
    category: 'Combos',
    price: 700,
    rating: 5.0,
    img: 'img20',
  },
];
export const toppings = [
  {
    id: 1,
    name: 'Tomato',
    price: 20,
    image: require('../assets/FoodDelivery/topings/pngwing 15.png'),
  },
  {
    id: 2,
    name: 'Onions',
    price: 15,
    image: require('../assets/FoodDelivery/topings/pngwing 16.png'),
  },
  {
    id: 3,
    name: 'Pickles',
    price: 25,
    image: require('../assets/FoodDelivery/topings/pngwing 17.png'),
  },
  {
    id: 4,
    name: 'Bacons',
    price: 40,
    image: require('../assets/FoodDelivery/topings/pngwing 18.png'),
  },
];

export const sideOptions = [
  {
    id: 5,
    name: 'Fries',
    price: 60,
    // image: require("../assets/fries.png"),
  },
  {
    id: 6,
    name: 'Coles',
    price: 50,
    // image: require("../assets/coleslaw.png"),
  },
  {
    id: 7,
    name: 'Salad',
    price: 70,
    // image: require("../assets/salad.png"),
  },
  {
    id: 8,
    name: 'Onion',
    price: 65,
    // image: require("../assets/onion-rings.png"),
  },
];
